"""Architecture document generator.

Analyzes repo structure, dependency graph, and service metadata to produce
a rich architecture.md and service_map.json.

When graph.json exists (from build-graph), the output includes per-service
dependencies, communication patterns, and a data flow overview.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

import yaml

from repo_brain.config import RepoConfig

logger = logging.getLogger(__name__)

# Service type display order and labels
SERVICE_TYPE_ORDER: list[tuple[str, str]] = [
    ("service", "Application Services"),
    ("mcp_server", "MCP Servers"),
    ("agent", "AI Agents"),
    ("library", "Shared Libraries"),
    ("data_store", "Data Stores"),
    ("init", "Init / Migration Jobs"),
]


def _build_repo_link(config: RepoConfig) -> str:
    """Build a clickable repo link with branch, or fall back to raw path."""
    url = config.remote_url
    if not url:
        return f"`{config.path}`"

    # Normalise to an HTTPS browsable URL
    browsable = url
    if browsable.startswith("git@"):
        # git@github.com:org/repo.git -> https://github.com/org/repo
        browsable = browsable.replace(":", "/", 1).replace("git@", "https://", 1)
    browsable = browsable.removesuffix(".git")

    branch_url = f"{browsable}/tree/{config.branch}"
    return f"[{browsable}]({branch_url})"


def generate_architecture(config: RepoConfig) -> str:
    """Analyze repo and generate architecture.md content.

    Uses graph.json (if available) to enrich output with dependency context,
    communication patterns, and data flow information.
    """
    repo_path = Path(config.path)
    sections: list[str] = []

    sections.append(f"# Architecture — {config.name}\n")
    repo_link = _build_repo_link(config)
    sections.append(f"Repository: {repo_link}\n")
    sections.append(f"Branch: `{config.branch}`\n")
    sections.append("---\n")

    # Detect all components
    services = _detect_services(repo_path)
    libraries = _detect_libraries(repo_path)
    compose_info = _parse_compose(repo_path)

    # Load graph data if available (from prior build-graph run)
    graph_data = _load_graph_data(config)

    # Enrich services with graph + compose + README data
    all_components = _enrich_components(services, libraries, compose_info, graph_data, repo_path)

    # Quick Reference table
    quick_ref = _build_quick_reference(all_components)
    if quick_ref:
        sections.append("## Quick Reference\n")
        sections.append(quick_ref)
        sections.append("")

    # Group components by type and render sections
    for type_key, type_label in SERVICE_TYPE_ORDER:
        components = [c for c in all_components if c.get("display_type") == type_key]
        if not components:
            continue
        sections.append(f"## {type_label}\n")
        for comp in components:
            sections.append(_render_component(comp))

    # Data stores from compose (if not already covered by graph)
    data_stores = compose_info.get("data_stores", [])
    standalone_stores = [
        s for s in data_stores if not any(c["name"] == s["name"] for c in all_components)
    ]
    if standalone_stores:
        sections.append("## Data Stores\n")
        for store in standalone_stores:
            sections.append(f"- **{store['name']}**: {store['type']}")
        sections.append("")

    # Data flow section from graph edges
    data_flow = _build_data_flow_section(graph_data)
    if data_flow:
        sections.append(data_flow)

    # Infrastructure
    infra = _detect_infrastructure(repo_path)
    if infra:
        sections.append("## Infrastructure\n")
        for item in infra:
            sections.append(f"- {item}")
        sections.append("")

    sections.append("---\n")
    sections.append(
        "*Auto-generated by repo-brain. "
        "Edit to add domain knowledge, data flow details, and gotchas. "
        "Your edits are preserved — re-running generate-docs will overwrite this file.*\n"
    )

    return "\n".join(sections)


def generate_service_map(config: RepoConfig) -> dict[str, Any]:
    """Generate a structured service map as JSON."""
    repo_path = Path(config.path)

    services = _detect_services(repo_path)
    libraries = _detect_libraries(repo_path)
    compose_info = _parse_compose(repo_path)
    graph_data = _load_graph_data(config)

    all_components = _enrich_components(services, libraries, compose_info, graph_data, repo_path)

    service_map: dict[str, Any] = {
        "repo": config.name,
        "services": {},
        "libraries": {},
        "data_stores": compose_info.get("data_stores", []),
        "service_dependencies": compose_info.get("dependencies", {}),
    }

    for comp in all_components:
        if comp.get("display_type") == "library":
            service_map["libraries"][comp["name"]] = {
                "path": comp.get("path", ""),
                "description": comp.get("description", ""),
                "upstream": comp.get("upstream_names", []),
                "downstream": comp.get("downstream_names", []),
            }
        else:
            service_map["services"][comp["name"]] = {
                "path": comp.get("path", ""),
                "type": comp.get("display_type", "service"),
                "language": comp.get("language", ""),
                "framework": comp.get("framework", ""),
                "description": comp.get("description", ""),
                "dependencies": comp.get("upstream_names", []),
                "dependents": comp.get("downstream_names", []),
                "data_stores": comp.get("data_stores", []),
                "grpc_services": comp.get("grpc_services", []),
            }

    return service_map


def save_generated_docs(config: RepoConfig) -> dict[str, str]:
    """Generate and save all architecture docs. Returns paths of created files."""
    config.docs_dir.mkdir(parents=True, exist_ok=True)
    created: dict[str, str] = {}

    # Detect components once — shared across generators
    repo_path = Path(config.path)
    services = _detect_services(repo_path)
    libraries = _detect_libraries(repo_path)
    compose_info = _parse_compose(repo_path)
    graph_data = _load_graph_data(config)
    all_components = _enrich_components(services, libraries, compose_info, graph_data, repo_path)

    # architecture.md
    arch_path = config.docs_dir / "architecture.md"
    arch_content = generate_architecture(config)
    arch_path.write_text(arch_content)
    created["architecture.md"] = str(arch_path)

    # service_map.json
    map_path = config.docs_dir / "service_map.json"
    service_map = generate_service_map(config)
    map_path.write_text(json.dumps(service_map, indent=2))
    created["service_map.json"] = str(map_path)

    # domain_terms.md
    terms_path = config.docs_dir / "domain_terms.md"
    terms_content = _generate_domain_terms(config, all_components, compose_info)
    terms_path.write_text(terms_content)
    created["domain_terms.md"] = str(terms_path)

    # gotchas.md
    gotchas_path = config.docs_dir / "gotchas.md"
    gotchas_content = _generate_gotchas(config, all_components, compose_info, graph_data)
    gotchas_path.write_text(gotchas_content)
    created["gotchas.md"] = str(gotchas_path)

    # Inject repo-brain pointer into AGENTS.md + write codebase overview
    agents_result = inject_agents_md(config, all_components, compose_info, graph_data)
    if "overview" in agents_result:
        created["codebase-overview.md"] = agents_result["overview"]
    if "agents_md" in agents_result:
        created["AGENTS.md"] = agents_result["agents_md"]

    return created


# ── AGENTS.md injection ──────────────────────────────────────────────

_SECTION_MARKER = "<!-- repo-brain:start -->"
_SECTION_MARKER_END = "<!-- repo-brain:end -->"

# Legacy markers from earlier versions that should be cleaned up
_LEGACY_MARKERS = [
    ("<!-- repo-brain:codebase-research -->", "<!-- repo-brain:codebase-research :end -->"),
]


def inject_agents_md(
    config: RepoConfig,
    components: list[dict[str, Any]] | None = None,
    compose_info: dict[str, Any] | None = None,
    graph_data: dict[str, Any] | None = None,
) -> dict[str, str]:
    """Inline codebase overview at the end of AGENTS.md and write a copy.

    1. Builds a compact overview section from repo data.
    2. Appends it (between markers) at the end of AGENTS.md — existing
       content above the markers is never modified.
    3. Also writes a copy to ``<repo>/.repo-brain/codebase-overview.md``
       (gitignored) for reference.

    Returns dict of written paths (keys: ``"agents_md"``, ``"overview"``).
    """
    repo_path = Path(config.path)
    written: dict[str, str] = {}

    # Build the section content
    overview = _generate_overview(config, components, compose_info, graph_data)
    section = f"{_SECTION_MARKER}\n{overview}\n{_SECTION_MARKER_END}"

    # ── 1. Write secondary copy to .repo-brain/codebase-overview.md ──
    overview_dir = repo_path / ".repo-brain"
    overview_dir.mkdir(exist_ok=True)
    overview_path = overview_dir / "codebase-overview.md"
    overview_path.write_text(overview + "\n")
    written["overview"] = str(overview_path)
    logger.info("Wrote codebase overview to %s", overview_path)

    _ensure_gitignore(repo_path, ".repo-brain/")

    # ── 2. Inline section at end of AGENTS.md ──
    agents_path = repo_path / "AGENTS.md"

    if agents_path.exists():
        content = agents_path.read_text()

        # Remove legacy markers
        for old_start, old_end in _LEGACY_MARKERS:
            if old_start in content:
                s = content.index(old_start)
                e = (
                    content.index(old_end) + len(old_end)
                    if old_end in content
                    else s + len(old_start)
                )
                before = content[:s].rstrip("\n")
                after = content[e:].lstrip("\n")
                content = before + "\n\n" + after if after else before + "\n"

        if _SECTION_MARKER in content:
            # Replace existing section
            s = content.index(_SECTION_MARKER)
            if _SECTION_MARKER_END in content:
                e = content.index(_SECTION_MARKER_END) + len(_SECTION_MARKER_END)
                existing = content[s:e]
            else:
                e = s + len(_SECTION_MARKER)
                existing = ""

            if existing == section:
                # Already up to date
                return written

            before = content[:s].rstrip("\n")
            after = content[e:].lstrip("\n")
            content = before + "\n" if not after else before + "\n\n" + after
        # else: no existing section, append below

        if not content.endswith("\n"):
            content += "\n"
        content += "\n" + section + "\n"
    else:
        content = section + "\n"

    agents_path.write_text(content)
    written["agents_md"] = str(agents_path)
    logger.info("Injected repo-brain section into %s", agents_path)

    return written


def _ensure_gitignore(repo_path: Path, entry: str) -> None:
    """Add *entry* to .gitignore if not already present."""
    gitignore = repo_path / ".gitignore"
    if gitignore.exists():
        text = gitignore.read_text()
        if entry in text:
            return
        if not text.endswith("\n"):
            text += "\n"
        text += f"\n# repo-brain generated files\n{entry}\n"
        gitignore.write_text(text)
    else:
        gitignore.write_text(f"# repo-brain generated files\n{entry}\n")


def _generate_overview(
    config: RepoConfig,
    components: list[dict[str, Any]] | None = None,
    compose_info: dict[str, Any] | None = None,
    graph_data: dict[str, Any] | None = None,
) -> str:
    """Build the codebase overview content.

    Target: ~300-500 tokens.  Includes architecture overview, key modules,
    dependency hotspots, gotchas, and MCP tool pointers.
    """
    lines: list[str] = ["## Codebase Overview", ""]

    # --- Project description ---
    repo_path = Path(config.path)
    meta = _read_project_metadata(repo_path)
    if meta.get("description"):
        lines.append(meta["description"])
        lines.append("")

    # --- Tech stack ---
    tech = _summarize_tech_stack(components or [], compose_info or {}, repo_path)
    if tech:
        lines.append(f"**Tech stack**: {tech}")
        lines.append("")

    # --- Directory structure (for non-microservice repos) ---
    if not components:
        dir_terms = _extract_directory_terms(repo_path)
        if dir_terms:
            lines.append("## Structure")
            for dirname, purpose in dir_terms[:10]:
                lines.append(f"- `{dirname}/` — {purpose}")
            lines.append("")

    # --- Modules / services (compact) ---
    if components:
        _append_component_summary(lines, components)

    # --- High-impact dependencies ---
    _append_dependency_hotspots(lines, components or [])

    # --- Gotchas (condensed) ---
    _append_gotcha_summary(lines, components or [], repo_path)

    # --- MCP tools ---
    lines.append("### repo-brain MCP Tools")
    lines.append(
        "This repo has a pre-built semantic index. "
        "Prefer these over grep/glob for codebase research:"
    )
    lines.append("- `scope_task(description)` — plan work: affected files, deps, risks")
    lines.append("- `search_code(query)` — semantic search by concept")

    return "\n".join(lines)


def _summarize_tech_stack(
    components: list[dict[str, Any]],
    compose_info: dict[str, Any],
    repo_path: Path,
) -> str:
    """Build a one-line tech stack summary."""
    parts: list[str] = []

    # Languages from components
    langs: set[str] = set()
    frameworks: set[str] = set()
    for comp in components:
        lang = comp.get("language", "")
        if lang:
            langs.add(lang.capitalize())
        fw = comp.get("framework", "")
        if fw:
            frameworks.add(fw)

    # Fallback: detect from repo root
    if not langs:
        if (repo_path / "pyproject.toml").exists():
            langs.add("Python")
        if (repo_path / "package.json").exists():
            langs.add("TypeScript")
        if (repo_path / "go.mod").exists():
            langs.add("Go")
        if (repo_path / "Cargo.toml").exists():
            langs.add("Rust")

    if langs:
        parts.append(", ".join(sorted(langs)))
    if frameworks:
        parts.append(", ".join(sorted(frameworks)))

    # Data stores from compose
    stores: set[str] = set()
    for ds in compose_info.get("data_stores", []):
        store_type = ds.get("type", "")
        if store_type:
            stores.add(store_type)
    if stores:
        parts.append(", ".join(sorted(stores)))

    return ", ".join(parts)


def _append_component_summary(
    lines: list[str],
    components: list[dict[str, Any]],
) -> None:
    """Append a compact module/service summary to lines."""
    # Group by type
    by_type: dict[str, list[dict[str, Any]]] = {}
    for comp in components:
        ctype = comp.get("display_type", "service")
        by_type.setdefault(ctype, []).append(comp)

    type_labels = {
        "service": "Services",
        "mcp_server": "MCP Servers",
        "agent": "Agents",
        "library": "Libraries",
        "data_store": "Data Stores",
        "init": "Init Jobs",
    }

    for type_key, label in type_labels.items():
        comps = by_type.get(type_key, [])
        if not comps:
            continue

        lines.append(f"### {label} ({len(comps)})")

        # Show top components (sorted by downstream count = most depended on)
        ranked = sorted(
            comps,
            key=lambda c: len(c.get("downstream_names", [])),
            reverse=True,
        )

        # Show up to 8 with detail, summarize the rest
        show_limit = 8
        for comp in ranked[:show_limit]:
            name = comp["name"]
            parts: list[str] = []

            # Path
            path = comp.get("path", "")
            if path:
                parts.append(f"`{path}`")

            # Brief description (truncated)
            desc = comp.get("description", "")
            if desc:
                if len(desc) > 80:
                    desc = desc[:77] + "..."
                parts.append(desc)

            # Dependency count if notable
            upstream = comp.get("upstream_names", comp.get("compose_depends_on", []))
            downstream = comp.get("downstream_names", [])
            dep_notes: list[str] = []
            if len(upstream) >= 3:
                dep_notes.append(f"{len(upstream)} deps")
            if len(downstream) >= 3:
                dep_notes.append(f"used by {len(downstream)}")
            if dep_notes:
                parts.append(f"({', '.join(dep_notes)})")

            detail = " — " + ", ".join(parts) if parts else ""
            lines.append(f"- **{name}**{detail}")

        remaining = len(comps) - show_limit
        if remaining > 0:
            rest_names = [c["name"] for c in ranked[show_limit:]]
            lines.append(f"- *+{remaining} more*: {', '.join(rest_names)}")

        lines.append("")


def _append_dependency_hotspots(
    lines: list[str],
    components: list[dict[str, Any]],
) -> None:
    """Append high-impact dependency info (most-depended-on components)."""
    # Find components depended on by 3+ others
    hotspots: list[tuple[str, int]] = []
    for comp in components:
        downstream = comp.get("downstream_names", [])
        if len(downstream) >= 3:
            hotspots.append((comp["name"], len(downstream)))

    if not hotspots:
        return

    hotspots.sort(key=lambda x: x[1], reverse=True)
    lines.append("### Dependency Hotspots")
    lines.append("Changes to these have wide blast radius:")
    for name, count in hotspots[:6]:
        lines.append(f"- **{name}** — {count} dependents")
    lines.append("")


def _append_gotcha_summary(
    lines: list[str],
    components: list[dict[str, Any]],
    repo_path: Path,
) -> None:
    """Append condensed gotchas (only if there are notable ones)."""
    gotchas: list[str] = []

    # Large files
    large_files = _find_large_files(repo_path, threshold=800)
    if large_files:
        top = large_files[0]
        gotchas.append(f"`{top[0]}` is {top[1]} lines — consider splitting")

    # High-dep services
    for comp in components:
        upstream = comp.get("upstream_names", comp.get("compose_depends_on", []))
        if len(upstream) >= 8:
            gotchas.append(
                f"**{comp['name']}** has {len(upstream)} dependencies — wide blast radius"
            )

    # gRPC services
    grpc_comps = [c for c in components if c.get("grpc_services")]
    if grpc_comps:
        names = ", ".join(c["name"] for c in grpc_comps[:3])
        gotchas.append(f"gRPC services ({names}) — proto changes require stub regeneration")

    if not gotchas:
        return

    lines.append("### Gotchas")
    for g in gotchas[:5]:
        lines.append(f"- {g}")
    lines.append("")


def _generate_domain_terms(
    config: RepoConfig,
    components: list[dict[str, Any]],
    compose_info: dict[str, Any],
) -> str:
    """Generate domain_terms.md with a glossary extracted from the codebase."""
    repo_path = Path(config.path)
    lines: list[str] = [
        f"# Domain Terms — {config.name}\n",
        "Auto-generated glossary of project terms and components.\n",
    ]

    # --- Project metadata from pyproject.toml / package.json ---
    project_meta = _read_project_metadata(repo_path)
    if project_meta.get("description"):
        lines.append(f"**Project**: {project_meta['description']}\n")

    # --- Key dependencies (external) ---
    ext_deps = project_meta.get("dependencies", [])
    if ext_deps:
        lines.append("## Key Dependencies\n")
        lines.append("| Package | Source |")
        lines.append("|---------|--------|")
        for dep in sorted(ext_deps)[:30]:  # cap to avoid huge tables
            lines.append(f"| {dep} | external |")
        lines.append("")

    # --- Directory structure as terms ---
    dir_terms = _extract_directory_terms(repo_path)
    if dir_terms:
        lines.append("## Project Structure\n")
        lines.append("| Directory | Purpose |")
        lines.append("|-----------|---------|")
        for dirname, purpose in dir_terms:
            lines.append(f"| `{dirname}` | {purpose} |")
        lines.append("")

    # --- Components (services, libraries, data stores — if present) ---
    if components:
        lines.append("## Components\n")
        lines.append("| Term | Type | Description |")
        lines.append("|------|------|-------------|")

        type_order = {
            "service": 1,
            "mcp_server": 2,
            "agent": 3,
            "library": 4,
            "data_store": 5,
            "init": 6,
        }
        sorted_comps = sorted(
            components,
            key=lambda c: (type_order.get(c.get("display_type", ""), 99), c["name"]),
        )

        seen: set[str] = set()
        for comp in sorted_comps:
            name = comp["name"]
            if name in seen:
                continue
            seen.add(name)
            ctype = comp.get("display_type", "")
            desc = comp.get("description", "")
            if len(desc) > 120:
                desc = desc[:117] + "..."
            desc = desc.replace("|", "\\|")
            lines.append(f"| {name} | {ctype} | {desc} |")
        lines.append("")

    lines.append("---\n")
    lines.append(
        "*Auto-generated by repo-brain. Re-running generate-docs will overwrite this file.*\n"
    )
    return "\n".join(lines)


def _generate_gotchas(
    config: RepoConfig,
    components: list[dict[str, Any]],
    compose_info: dict[str, Any],
    graph_data: dict[str, Any] | None,
) -> str:
    """Generate gotchas.md with auto-detected complexity hotspots and warnings."""
    repo_path = Path(config.path)
    lines: list[str] = [
        f"# Gotchas — {config.name}\n",
        "Auto-detected complexity hotspots and dependency warnings.\n",
    ]

    has_content = False

    # --- Large files (any repo) ---
    large_files = _find_large_files(repo_path)
    if large_files:
        has_content = True
        lines.append("## Large Files\n")
        lines.append("These files are unusually large and may be hard to maintain.\n")
        for fpath, line_count in large_files:
            lines.append(f"- `{fpath}` ({line_count} lines)")
        lines.append("")

    # --- Deeply nested directories (any repo) ---
    deep_dirs = _find_deep_directories(repo_path)
    if deep_dirs:
        has_content = True
        lines.append("## Deep Directory Nesting\n")
        lines.append("Deeply nested paths can signal overly complex module structure.\n")
        for d in deep_dirs:
            lines.append(f"- `{d}`")
        lines.append("")

    # --- High-dependency services (microservices) ---
    high_dep: list[tuple[str, int, list[str]]] = []
    for comp in components:
        upstream = comp.get("upstream_names", comp.get("compose_depends_on", []))
        if len(upstream) >= 4:
            high_dep.append((comp["name"], len(upstream), upstream))

    if high_dep:
        has_content = True
        high_dep.sort(key=lambda x: x[1], reverse=True)
        lines.append("## High-Dependency Services\n")
        lines.append(
            "These services depend on many others — changes to their "
            "dependencies have a wide blast radius.\n"
        )
        for name, count, deps in high_dep:
            lines.append(f"- **{name}** ({count} dependencies): {', '.join(deps)}")
        lines.append("")

    # --- Heavily depended-on components ---
    high_dependents: list[tuple[str, int, list[str]]] = []
    for comp in components:
        downstream = comp.get("downstream_names", [])
        if len(downstream) >= 3:
            high_dependents.append((comp["name"], len(downstream), downstream))

    if high_dependents:
        has_content = True
        high_dependents.sort(key=lambda x: x[1], reverse=True)
        lines.append("## Widely Used Components\n")
        lines.append("Breaking changes in these components affect many consumers.\n")
        for name, count, deps in high_dependents:
            lines.append(f"- **{name}** (used by {count}): {', '.join(deps)}")
        lines.append("")

    # --- Init containers ---
    init_services = [c for c in components if c.get("display_type") == "init"]
    if init_services:
        has_content = True
        lines.append("## Init / Migration Containers\n")
        lines.append("These must run before their dependent services are healthy.\n")
        for comp in init_services:
            upstream = comp.get("upstream_names", comp.get("compose_depends_on", []))
            dep_str = f" (requires: {', '.join(upstream)})" if upstream else ""
            lines.append(f"- **{comp['name']}**{dep_str}")
        lines.append("")

    # --- Shared data stores ---
    store_users: dict[str, list[str]] = {}
    for comp in components:
        for store in comp.get("data_stores", []):
            store_users.setdefault(store, []).append(comp["name"])

    shared_stores = {s: users for s, users in store_users.items() if len(users) >= 2}
    if shared_stores:
        has_content = True
        lines.append("## Shared Data Stores\n")
        lines.append(
            "Multiple services write to these stores — watch for "
            "schema migration conflicts and race conditions.\n"
        )
        for store, users in sorted(shared_stores.items(), key=lambda x: len(x[1]), reverse=True):
            lines.append(f"- **{store}** ({len(users)} services): {', '.join(users)}")
        lines.append("")

    # --- gRPC services ---
    grpc_comps = [c for c in components if c.get("grpc_services")]
    if grpc_comps:
        has_content = True
        lines.append("## gRPC Services\n")
        lines.append("Proto changes require regenerating stubs in all consumers.\n")
        for comp in grpc_comps:
            lines.append(f"- **{comp['name']}**: {', '.join(comp['grpc_services'])}")
        lines.append("")

    if not has_content:
        lines.append("No gotchas detected automatically.\n")

    lines.append("---\n")
    lines.append(
        "*Auto-generated by repo-brain. Re-running generate-docs will overwrite this file.*\n"
    )
    return "\n".join(lines)


# --- Generic repo analysis helpers ---

_SKIP_DIRS = {
    ".git",
    ".venv",
    "venv",
    "node_modules",
    "__pycache__",
    "dist",
    "build",
    ".ruff_cache",
    ".mypy_cache",
    ".pytest_cache",
    ".tox",
    ".eggs",
    "egg-info",
    ".next",
    ".nuxt",
    "coverage",
}

_DIR_PURPOSE: dict[str, str] = {
    "src": "Source code",
    "lib": "Library code",
    "app": "Application entry point",
    "api": "API layer",
    "core": "Core business logic",
    "config": "Configuration",
    "configs": "Configuration",
    "utils": "Utility helpers",
    "helpers": "Utility helpers",
    "common": "Shared code",
    "shared": "Shared code",
    "models": "Data models",
    "schemas": "Data schemas",
    "services": "Service layer / microservices",
    "controllers": "Request handlers",
    "routes": "Route definitions",
    "handlers": "Request/event handlers",
    "middleware": "Middleware",
    "views": "View layer",
    "templates": "Templates",
    "static": "Static assets",
    "public": "Public assets",
    "assets": "Assets",
    "components": "UI components",
    "pages": "Page components",
    "hooks": "React/custom hooks",
    "store": "State management",
    "stores": "State management",
    "tests": "Tests",
    "test": "Tests",
    "spec": "Tests / specs",
    "fixtures": "Test fixtures",
    "migrations": "Database migrations",
    "alembic": "Alembic migrations",
    "scripts": "Utility scripts",
    "bin": "Executables / scripts",
    "tools": "Developer tools",
    "docs": "Documentation",
    "deploy": "Deployment configs",
    "infra": "Infrastructure as code",
    "terraform": "Terraform IaC",
    "helm": "Helm charts",
    "k8s": "Kubernetes manifests",
    "docker": "Docker configs",
    ".github": "GitHub workflows / config",
    "ci": "CI/CD config",
    "agents": "AI agents",
    "mcp_servers": "MCP servers",
    "libraries": "Shared libraries",
    "proto": "Protocol Buffer definitions",
    "protos": "Protocol Buffer definitions",
    "grpc": "gRPC service layer",
}

_CODE_EXTENSIONS = {
    ".py",
    ".js",
    ".ts",
    ".tsx",
    ".jsx",
    ".go",
    ".rs",
    ".java",
    ".rb",
    ".php",
    ".cs",
    ".cpp",
    ".c",
    ".h",
    ".swift",
    ".kt",
    ".scala",
    ".vue",
    ".svelte",
}


def _read_project_metadata(repo_path: Path) -> dict[str, Any]:
    """Read project metadata from pyproject.toml or package.json at repo root."""
    meta: dict[str, Any] = {}

    pyproject = repo_path / "pyproject.toml"
    if pyproject.exists():
        try:
            try:
                import tomllib
            except ImportError:
                import tomli as tomllib  # type: ignore[no-redef]

            data = tomllib.loads(pyproject.read_text())
            project = data.get("project", {})
            meta["name"] = project.get("name", "")
            meta["description"] = project.get("description", "")
            raw_deps = project.get("dependencies", [])
            # Extract just package names (strip versions)
            deps = []
            for dep in raw_deps:
                if isinstance(dep, str):
                    name = dep.split(">=")[0].split("<=")[0].split("==")[0]
                    name = name.split("~=")[0].split("[")[0].split("@")[0].strip()
                    if name:
                        deps.append(name)
            meta["dependencies"] = deps
        except Exception:
            pass

    pkg_json = repo_path / "package.json"
    if pkg_json.exists() and not meta.get("name"):
        try:
            data = json.loads(pkg_json.read_text())
            meta["name"] = data.get("name", "")
            meta["description"] = data.get("description", "")
            deps = list(data.get("dependencies", {}).keys())
            deps += list(data.get("devDependencies", {}).keys())
            meta["dependencies"] = deps
        except Exception:
            pass

    return meta


def _extract_directory_terms(repo_path: Path) -> list[tuple[str, str]]:
    """Extract top-level directories and infer their purpose."""
    terms: list[tuple[str, str]] = []
    try:
        entries = sorted(repo_path.iterdir())
    except OSError:
        return terms

    for entry in entries:
        if not entry.is_dir():
            continue
        name = entry.name
        if name in _SKIP_DIRS or name.startswith("."):
            continue
        purpose = _DIR_PURPOSE.get(name, "")
        if not purpose:
            # Try to infer from contents
            purpose = _infer_dir_purpose(entry)
        if purpose:
            terms.append((name, purpose))

    return terms


def _infer_dir_purpose(directory: Path) -> str:
    """Try to infer a directory's purpose from its contents."""
    try:
        children = list(directory.iterdir())
    except OSError:
        return ""

    child_names = {c.name for c in children}

    if "Dockerfile" in child_names or "docker-compose.yml" in child_names:
        return "Containerized service"
    if "pyproject.toml" in child_names:
        return "Python package"
    if "package.json" in child_names:
        return "Node.js package"
    if "go.mod" in child_names:
        return "Go module"
    if "Cargo.toml" in child_names:
        return "Rust crate"
    if any(c.suffix == ".proto" for c in children if c.is_file()):
        return "Protocol Buffer definitions"
    if any(c.suffix == ".md" for c in children if c.is_file()):
        has_code = any(c.suffix in _CODE_EXTENSIONS for c in children if c.is_file())
        if not has_code:
            return "Documentation"
    return ""


def _find_large_files(
    repo_path: Path,
    threshold: int = 500,
) -> list[tuple[str, int]]:
    """Find source files exceeding a line threshold."""
    large: list[tuple[str, int]] = []

    for ext in _CODE_EXTENSIONS:
        for fpath in repo_path.rglob(f"*{ext}"):
            if any(skip in fpath.parts for skip in _SKIP_DIRS):
                continue
            try:
                line_count = sum(1 for _ in fpath.open())
                if line_count >= threshold:
                    rel = str(fpath.relative_to(repo_path))
                    large.append((rel, line_count))
            except (OSError, UnicodeDecodeError):
                continue

    large.sort(key=lambda x: x[1], reverse=True)
    return large[:15]  # Top 15


def _find_deep_directories(
    repo_path: Path,
    threshold: int = 7,
) -> list[str]:
    """Find directories with nesting deeper than threshold levels."""
    deep: list[str] = []

    for dirpath in repo_path.rglob("*"):
        if not dirpath.is_dir():
            continue
        if any(skip in dirpath.parts for skip in _SKIP_DIRS):
            continue
        try:
            rel = dirpath.relative_to(repo_path)
        except ValueError:
            continue
        if len(rel.parts) >= threshold:
            deep.append(str(rel))

    deep.sort()
    return deep[:10]  # Cap output


# --- Enrichment pipeline ---


def _load_graph_data(config: RepoConfig) -> dict[str, Any] | None:
    """Load graph.json if it exists from a prior build-graph run."""
    if not config.graph_path.exists():
        return None
    try:
        import networkx as nx

        data = json.loads(config.graph_path.read_text())
        graph = nx.node_link_graph(data)
        return {"graph": graph}
    except Exception as e:
        logger.warning("Failed to load graph data: %s", e)
        return None


def _enrich_components(
    services: list[dict[str, Any]],
    libraries: list[dict[str, Any]],
    compose_info: dict[str, Any],
    graph_data: dict[str, Any] | None,
    repo_path: Path,
) -> list[dict[str, Any]]:
    """Merge all data sources into a unified component list."""
    components: list[dict[str, Any]] = []
    compose_deps = compose_info.get("dependencies", {})
    compose_services = compose_info.get("services_raw", {})

    # Process services
    for svc in services:
        comp = dict(svc)
        comp["display_type"] = svc.get("type", "service")

        # Add compose dependencies
        deps = compose_deps.get(svc["name"], [])
        if deps:
            comp["compose_depends_on"] = deps

        # Try to get richer description from service README
        readme_desc = _extract_readme_description(repo_path, svc.get("path", ""))
        if readme_desc and (
            not comp.get("description") or len(readme_desc) > len(comp.get("description", ""))
        ):
            comp["description"] = readme_desc

        # Enrich from graph data
        if graph_data:
            _enrich_from_graph(comp, graph_data)

        # Identify data stores this service uses (from compose depends_on)
        data_store_deps = []
        for dep in deps:
            dep_config = compose_services.get(dep, {})
            if _is_data_store_name(dep, dep_config):
                data_store_deps.append(dep)
        if data_store_deps:
            comp["data_stores"] = data_store_deps

        components.append(comp)

    # Process libraries
    for lib in libraries:
        comp = dict(lib)
        comp["display_type"] = "library"

        readme_desc = _extract_readme_description(repo_path, lib.get("path", ""))
        if readme_desc and (
            not comp.get("description") or len(readme_desc) > len(comp.get("description", ""))
        ):
            comp["description"] = readme_desc

        if graph_data:
            _enrich_from_graph(comp, graph_data)

        components.append(comp)

    # Add data stores from compose that aren't already in the list
    data_stores = compose_info.get("data_stores", [])
    existing_names = {c["name"] for c in components}
    for store in data_stores:
        if store["name"] not in existing_names:
            comp: dict[str, Any] = {
                "name": store["name"],
                "display_type": "data_store",
                "description": store["type"],
                "path": "",
            }
            if graph_data:
                _enrich_from_graph(comp, graph_data)
            components.append(comp)

    # Add init services from compose that aren't already in the list
    for svc_name, svc_config in compose_services.items():
        if svc_name not in existing_names and _is_init_service(svc_name, svc_config):
            comp = {
                "name": svc_name,
                "display_type": "init",
                "description": "",
                "path": "",
                "compose_depends_on": compose_deps.get(svc_name, []),
            }
            if graph_data:
                _enrich_from_graph(comp, graph_data)
            components.append(comp)
            existing_names.add(svc_name)

    return components


def _enrich_from_graph(comp: dict[str, Any], graph_data: dict[str, Any]) -> None:
    """Add upstream/downstream/gRPC info from the dependency graph."""
    graph = graph_data["graph"]
    name = comp["name"]

    if name not in graph:
        return

    node_attrs = dict(graph.nodes[name])

    # Upstream (what this component depends on)
    upstream = [succ for succ in graph.successors(name)]
    if upstream:
        comp["upstream_names"] = upstream

    # Downstream (what depends on this component)
    downstream = [pred for pred in graph.predecessors(name)]
    if downstream:
        comp["downstream_names"] = downstream

    # gRPC services
    grpc_services = node_attrs.get("grpc_services", [])
    if grpc_services:
        comp["grpc_services"] = grpc_services

    grpc_rpcs = node_attrs.get("grpc_rpcs", [])
    if grpc_rpcs:
        comp["grpc_rpcs"] = grpc_rpcs

    # Component type from graph (more accurate than dir-based detection)
    if node_attrs.get("component_type"):
        comp["graph_component_type"] = node_attrs["component_type"]

    # Package name
    if node_attrs.get("package_name"):
        comp["package_name"] = node_attrs["package_name"]

    # Graph description (from pyproject.toml, may be richer)
    graph_desc = node_attrs.get("description", "")
    if graph_desc and not comp.get("description"):
        comp["description"] = graph_desc


def _extract_readme_description(repo_path: Path, service_path: str) -> str:
    """Extract the first meaningful paragraph from a service's README.md."""
    if not service_path:
        return ""

    readme_path = repo_path / service_path / "README.md"
    if not readme_path.exists():
        # Try lowercase
        readme_path = repo_path / service_path / "readme.md"
    if not readme_path.exists():
        return ""

    try:
        content = readme_path.read_text(errors="replace")
    except Exception:
        return ""

    # Extract first non-heading, non-empty paragraph
    lines = content.splitlines()
    paragraph_lines: list[str] = []
    found_content = False

    for line in lines:
        stripped = line.strip()

        # Skip headings, badges, empty lines at the start
        if not found_content:
            if (
                not stripped
                or stripped.startswith("#")
                or stripped.startswith("![")
                or stripped.startswith("[!")
            ):
                continue
            found_content = True

        if found_content:
            if not stripped:
                # End of paragraph
                if paragraph_lines:
                    break
                continue
            if stripped.startswith("#"):
                # Next heading, stop
                break
            paragraph_lines.append(stripped)

    result = " ".join(paragraph_lines).strip()
    # Cap at a reasonable length
    if len(result) > 300:
        result = result[:297] + "..."
    return result


def _render_component(comp: dict[str, Any]) -> str:
    """Render a single component as a markdown section."""
    lines: list[str] = []
    lines.append(f"### {comp['name']}\n")

    # Basic info line (compact)
    info_parts: list[str] = []
    if comp.get("path"):
        info_parts.append(f"**Path**: `{comp['path']}`")
    if comp.get("language"):
        info_parts.append(f"**Language**: {comp['language']}")
    if comp.get("framework"):
        info_parts.append(f"**Framework**: {comp['framework']}")
    if info_parts:
        lines.append("- " + " | ".join(info_parts))

    # Description
    if comp.get("description"):
        lines.append(f"- **Description**: {comp['description']}")

    # Dependencies (from graph or compose)
    upstream = comp.get("upstream_names", [])
    if not upstream:
        upstream = comp.get("compose_depends_on", [])
    if upstream:
        lines.append(f"- **Depends on**: {', '.join(upstream)}")

    # Dependents
    downstream = comp.get("downstream_names", [])
    if downstream:
        lines.append(f"- **Depended on by**: {', '.join(downstream)}")

    # Data stores
    data_stores = comp.get("data_stores", [])
    if data_stores:
        lines.append(f"- **Data stores**: {', '.join(data_stores)}")

    # gRPC services
    grpc = comp.get("grpc_services", [])
    if grpc:
        lines.append(f"- **gRPC services**: {', '.join(grpc)}")

    lines.append("")
    return "\n".join(lines)


def _build_quick_reference(components: list[dict[str, Any]]) -> str:
    """Build a compact quick reference table."""
    if not components:
        return ""

    lines: list[str] = []
    lines.append("| Component | Type | Language | Key Dependencies |")
    lines.append("|-----------|------|----------|-----------------|")

    for comp in components:
        name = comp["name"]
        ctype = comp.get("display_type", "")
        lang = comp.get("language", "")
        deps = comp.get("upstream_names", comp.get("compose_depends_on", []))
        deps_str = ", ".join(deps[:4])
        if len(deps) > 4:
            deps_str += f" (+{len(deps) - 4})"
        lines.append(f"| {name} | {ctype} | {lang} | {deps_str} |")

    return "\n".join(lines)


def _build_data_flow_section(graph_data: dict[str, Any] | None) -> str:
    """Build a data flow section from graph edges, grouped by type."""
    if not graph_data:
        return ""

    graph = graph_data["graph"]
    if graph.number_of_edges() == 0:
        return ""

    lines: list[str] = []
    lines.append("## Communication Patterns\n")

    # Group edges by type
    edge_groups: dict[str, list[tuple[str, str]]] = {}
    for src, tgt, attrs in graph.edges(data=True):
        edge_type = attrs.get("edge_type", "depends_on")
        if edge_type not in edge_groups:
            edge_groups[edge_type] = []
        edge_groups[edge_type].append((src, tgt))

    type_labels = {
        "depends_on": "Service Dependencies",
        "uses_datastore": "Data Store Usage",
        "grpc": "gRPC Communication",
        "library_dep": "Library Dependencies",
    }

    for edge_type, edges in edge_groups.items():
        label = type_labels.get(edge_type, edge_type)
        lines.append(f"### {label}\n")
        for src, tgt in edges:
            lines.append(f"- {src} -> {tgt}")
        lines.append("")

    return "\n".join(lines)


# --- Detection helpers ---


def _detect_services(repo_path: Path) -> list[dict[str, Any]]:
    """Detect microservices in the repo."""
    services: list[dict[str, Any]] = []

    services_dir = repo_path / "services"
    if services_dir.exists():
        for svc_dir in sorted(services_dir.iterdir()):
            if not svc_dir.is_dir() or svc_dir.name.startswith("."):
                continue
            svc: dict[str, Any] = {
                "name": svc_dir.name,
                "path": f"services/{svc_dir.name}",
                "type": "service",
            }
            _detect_service_tech(svc_dir, svc)
            services.append(svc)

    # Check for MCP servers
    mcp_dir = repo_path / "mcp_servers"
    if mcp_dir.exists():
        for svc_dir in sorted(mcp_dir.iterdir()):
            if not svc_dir.is_dir() or svc_dir.name.startswith("."):
                continue
            svc = {
                "name": svc_dir.name,
                "path": f"mcp_servers/{svc_dir.name}",
                "type": "mcp_server",
            }
            _detect_service_tech(svc_dir, svc)
            services.append(svc)

    # Check for agents
    agents_dir = repo_path / "agents"
    if agents_dir.exists():
        for svc_dir in sorted(agents_dir.iterdir()):
            if not svc_dir.is_dir() or svc_dir.name.startswith("."):
                continue
            svc = {
                "name": svc_dir.name,
                "path": f"agents/{svc_dir.name}",
                "type": "agent",
            }
            _detect_service_tech(svc_dir, svc)
            services.append(svc)

    return services


def _detect_service_tech(svc_dir: Path, svc: dict[str, Any]) -> None:
    """Detect language and framework for a service directory."""
    # Python
    if list(svc_dir.rglob("pyproject.toml")):
        svc["language"] = "python"
        for req_file in svc_dir.rglob("pyproject.toml"):
            try:
                content = req_file.read_text()
                if "fastapi" in content.lower():
                    svc["framework"] = "FastAPI"
                elif "flask" in content.lower():
                    svc["framework"] = "Flask"
                elif "langchain" in content.lower() or "langgraph" in content.lower():
                    svc["framework"] = "LangChain/LangGraph"
                # Try to extract description
                if "description" in content:
                    for line in content.splitlines():
                        if line.strip().startswith("description"):
                            desc = line.split("=", 1)[-1].strip().strip('"').strip("'")
                            if desc:
                                svc["description"] = desc
                            break
            except Exception:
                pass

    # Go
    elif list(svc_dir.rglob("go.mod")):
        svc["language"] = "go"
        for mod_file in svc_dir.rglob("go.mod"):
            try:
                content = mod_file.read_text()
                if "gin-gonic" in content:
                    svc["framework"] = "Gin"
            except Exception:
                pass

    # TypeScript/JavaScript
    elif list(svc_dir.rglob("package.json")):
        svc["language"] = "typescript"
        for pkg_file in svc_dir.rglob("package.json"):
            try:
                content = pkg_file.read_text()
                if "react" in content:
                    svc["framework"] = "React"
                elif "express" in content:
                    svc["framework"] = "Express"
                elif "next" in content:
                    svc["framework"] = "Next.js"
            except Exception:
                pass

    # Rust
    elif list(svc_dir.rglob("Cargo.toml")):
        svc["language"] = "rust"


def _detect_libraries(repo_path: Path) -> list[dict[str, Any]]:
    """Detect shared libraries."""
    libraries: list[dict[str, Any]] = []

    # Check common library directory names
    lib_dirs = ["libraries", "libs", "packages"]
    for lib_dir_name in lib_dirs:
        libs_dir = repo_path / lib_dir_name
        if not libs_dir.exists():
            continue
        # Handle nested structure like libraries/python/<lib>
        for child in sorted(libs_dir.iterdir()):
            if not child.is_dir() or child.name.startswith("."):
                continue
            # Check if this is a direct library or a language group
            if _has_project_file(child):
                lib = _build_lib_entry(child, f"{lib_dir_name}/{child.name}")
                libraries.append(lib)
            else:
                # Could be libraries/python/<lib>, libraries/go/<lib>, etc.
                for sub in sorted(child.iterdir()):
                    if not sub.is_dir() or sub.name.startswith("."):
                        continue
                    if _has_project_file(sub):
                        lib = _build_lib_entry(sub, f"{lib_dir_name}/{child.name}/{sub.name}")
                        libraries.append(lib)

    return libraries


def _has_project_file(directory: Path) -> bool:
    """Check if a directory has a project file (pyproject.toml, package.json, etc.)."""
    return any(
        (directory / f).exists() for f in ["pyproject.toml", "package.json", "Cargo.toml", "go.mod"]
    )


def _build_lib_entry(lib_dir: Path, rel_path: str) -> dict[str, Any]:
    """Build a library entry from a directory."""
    lib: dict[str, Any] = {
        "name": lib_dir.name,
        "path": rel_path,
    }
    # Try to get description from pyproject.toml
    for toml_file in lib_dir.rglob("pyproject.toml"):
        try:
            content = toml_file.read_text()
            for line in content.splitlines():
                if line.strip().startswith("description"):
                    desc = line.split("=", 1)[-1].strip().strip('"').strip("'")
                    if desc:
                        lib["description"] = desc
                    break
        except Exception:
            pass
    return lib


def _parse_compose(repo_path: Path) -> dict[str, Any]:
    """Parse Docker Compose file for service topology."""
    result: dict[str, Any] = {"data_stores": [], "dependencies": {}, "services_raw": {}}

    compose_file = repo_path / "compose.yml"
    if not compose_file.exists():
        compose_file = repo_path / "docker-compose.yml"
    if not compose_file.exists():
        compose_file = repo_path / "docker-compose.yaml"
    if not compose_file.exists():
        return result

    try:
        data = yaml.safe_load(compose_file.read_text())
    except Exception as e:
        logger.warning("Failed to parse compose file: %s", e)
        return result

    if not data or "services" not in data:
        return result

    # Known data store images
    data_store_patterns = {
        "postgres": "PostgreSQL",
        "timescaledb": "TimescaleDB",
        "neo4j": "Neo4j",
        "chromadb": "ChromaDB",
        "chroma": "ChromaDB",
        "redis": "Redis",
        "kafka": "Kafka",
        "minio": "MinIO/S3",
        "langfuse": "Langfuse",
    }

    for svc_name, svc_config in data.get("services", {}).items():
        if not isinstance(svc_config, dict):
            continue

        result["services_raw"][svc_name] = svc_config
        image = svc_config.get("image", "")

        # Detect data stores
        for pattern, store_type in data_store_patterns.items():
            if pattern in svc_name.lower() or pattern in image.lower():
                result["data_stores"].append({"name": svc_name, "type": store_type})
                break

        # Detect dependencies
        depends_on = svc_config.get("depends_on", [])
        if isinstance(depends_on, dict):
            deps = list(depends_on.keys())
        elif isinstance(depends_on, list):
            deps = depends_on
        else:
            deps = []

        if deps:
            result["dependencies"][svc_name] = deps

    return result


def _is_data_store_name(name: str, config: dict[str, Any]) -> bool:
    """Check if a compose service name looks like a data store."""
    image = ""
    if isinstance(config, dict):
        image = config.get("image", "")
    patterns = [
        "postgres",
        "timescaledb",
        "neo4j",
        "chromadb",
        "chroma",
        "redis",
        "kafka",
        "minio",
        "langfuse",
    ]
    for p in patterns:
        if p in name.lower() or p in image.lower():
            return True
    return False


def _is_init_service(name: str, config: dict[str, Any]) -> bool:
    """Check if a compose service is an init/migration service."""
    init_patterns = {"init", "migrations", "setup"}
    for pattern in init_patterns:
        if pattern in name.lower():
            return True
    if isinstance(config, dict) and config.get("restart") == "no":
        return True
    return False


def _detect_infrastructure(repo_path: Path) -> list[str]:
    """Detect infrastructure tooling."""
    infra: list[str] = []

    if (repo_path / "helm-charts").exists():
        chart_count = len(list((repo_path / "helm-charts").glob("*/Chart.yaml")))
        if chart_count == 0:
            # Try nested structure
            chart_count = len(list((repo_path / "helm-charts").rglob("Chart.yaml")))
        infra.append(f"Helm charts: {chart_count} charts")

    if (repo_path / "infrastructure").exists():
        infra.append("Infrastructure as Code (Terraform/OpenTofu)")

    if (repo_path / ".github" / "workflows").exists():
        wf_count = len(list((repo_path / ".github" / "workflows").glob("*.yml")))
        infra.append(f"GitHub Actions: {wf_count} workflows")

    if (repo_path / "justfile").exists():
        infra.append("Task runner: Just")

    if (repo_path / "Makefile").exists():
        infra.append("Task runner: Make")

    if (repo_path / "monitoring").exists():
        infra.append("Monitoring: Grafana + Prometheus")

    if (repo_path / "skaffold.yaml").exists():
        infra.append("Skaffold: local Kubernetes development")

    return infra
