"""Architecture document generator.

Analyzes repo structure, dependency graph, and service metadata to produce
a rich architecture.md and service_map.json.

When graph.json exists (from build-graph), the output includes per-service
dependencies, communication patterns, and a data flow overview.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

import yaml

from repo_brain.config import RepoConfig

logger = logging.getLogger(__name__)

# Service type display order and labels
SERVICE_TYPE_ORDER: list[tuple[str, str]] = [
    ("service", "Application Services"),
    ("mcp_server", "MCP Servers"),
    ("agent", "AI Agents"),
    ("library", "Shared Libraries"),
    ("data_store", "Data Stores"),
    ("init", "Init / Migration Jobs"),
]


def generate_architecture(config: RepoConfig) -> str:
    """Analyze repo and generate architecture.md content.

    Uses graph.json (if available) to enrich output with dependency context,
    communication patterns, and data flow information.
    """
    repo_path = Path(config.path)
    sections: list[str] = []

    sections.append(f"# Architecture — {config.name}\n")
    sections.append(f"Repository: `{config.remote_url or config.path}`\n")
    sections.append("---\n")

    # Detect all components
    services = _detect_services(repo_path)
    libraries = _detect_libraries(repo_path)
    compose_info = _parse_compose(repo_path)

    # Load graph data if available (from prior build-graph run)
    graph_data = _load_graph_data(config)

    # Enrich services with graph + compose + README data
    all_components = _enrich_components(services, libraries, compose_info, graph_data, repo_path)

    # Quick Reference table
    quick_ref = _build_quick_reference(all_components)
    if quick_ref:
        sections.append("## Quick Reference\n")
        sections.append(quick_ref)
        sections.append("")

    # Group components by type and render sections
    for type_key, type_label in SERVICE_TYPE_ORDER:
        components = [c for c in all_components if c.get("display_type") == type_key]
        if not components:
            continue
        sections.append(f"## {type_label}\n")
        for comp in components:
            sections.append(_render_component(comp))

    # Data stores from compose (if not already covered by graph)
    data_stores = compose_info.get("data_stores", [])
    standalone_stores = [
        s for s in data_stores if not any(c["name"] == s["name"] for c in all_components)
    ]
    if standalone_stores:
        sections.append("## Data Stores\n")
        for store in standalone_stores:
            sections.append(f"- **{store['name']}**: {store['type']}")
        sections.append("")

    # Data flow section from graph edges
    data_flow = _build_data_flow_section(graph_data)
    if data_flow:
        sections.append(data_flow)

    # Infrastructure
    infra = _detect_infrastructure(repo_path)
    if infra:
        sections.append("## Infrastructure\n")
        for item in infra:
            sections.append(f"- {item}")
        sections.append("")

    sections.append("---\n")
    sections.append(
        "*Auto-generated by repo-brain. "
        "Edit to add domain knowledge, data flow details, and gotchas. "
        "Your edits are preserved — re-running generate-docs will overwrite this file.*\n"
    )

    return "\n".join(sections)


def generate_service_map(config: RepoConfig) -> dict[str, Any]:
    """Generate a structured service map as JSON."""
    repo_path = Path(config.path)

    services = _detect_services(repo_path)
    libraries = _detect_libraries(repo_path)
    compose_info = _parse_compose(repo_path)
    graph_data = _load_graph_data(config)

    all_components = _enrich_components(services, libraries, compose_info, graph_data, repo_path)

    service_map: dict[str, Any] = {
        "repo": config.name,
        "services": {},
        "libraries": {},
        "data_stores": compose_info.get("data_stores", []),
        "service_dependencies": compose_info.get("dependencies", {}),
    }

    for comp in all_components:
        if comp.get("display_type") == "library":
            service_map["libraries"][comp["name"]] = {
                "path": comp.get("path", ""),
                "description": comp.get("description", ""),
                "upstream": comp.get("upstream_names", []),
                "downstream": comp.get("downstream_names", []),
            }
        else:
            service_map["services"][comp["name"]] = {
                "path": comp.get("path", ""),
                "type": comp.get("display_type", "service"),
                "language": comp.get("language", ""),
                "framework": comp.get("framework", ""),
                "description": comp.get("description", ""),
                "dependencies": comp.get("upstream_names", []),
                "dependents": comp.get("downstream_names", []),
                "data_stores": comp.get("data_stores", []),
                "grpc_services": comp.get("grpc_services", []),
            }

    return service_map


def save_generated_docs(config: RepoConfig) -> dict[str, str]:
    """Generate and save all architecture docs. Returns paths of created files."""
    config.docs_dir.mkdir(parents=True, exist_ok=True)
    created: dict[str, str] = {}

    # architecture.md
    arch_path = config.docs_dir / "architecture.md"
    arch_content = generate_architecture(config)
    arch_path.write_text(arch_content)
    created["architecture.md"] = str(arch_path)

    # service_map.json
    map_path = config.docs_dir / "service_map.json"
    service_map = generate_service_map(config)
    map_path.write_text(json.dumps(service_map, indent=2))
    created["service_map.json"] = str(map_path)

    # domain_terms.md (skeleton)
    terms_path = config.docs_dir / "domain_terms.md"
    if not terms_path.exists():
        terms_path.write_text(
            f"# Domain Terms — {config.name}\n\n"
            "Add business vocabulary and internal naming conventions here.\n\n"
            "| Term | Meaning |\n"
            "|------|--------|\n"
            "| | |\n"
        )
        created["domain_terms.md"] = str(terms_path)

    # gotchas.md (skeleton)
    gotchas_path = config.docs_dir / "gotchas.md"
    if not gotchas_path.exists():
        gotchas_path.write_text(
            f"# Gotchas — {config.name}\n\n"
            "Document traps, edge cases, and common mistakes here.\n\n"
            "## Known Issues\n\n"
            "## Common Mistakes\n\n"
            "## Edge Cases\n"
        )
        created["gotchas.md"] = str(gotchas_path)

    return created


# --- Enrichment pipeline ---


def _load_graph_data(config: RepoConfig) -> dict[str, Any] | None:
    """Load graph.json if it exists from a prior build-graph run."""
    if not config.graph_path.exists():
        return None
    try:
        import networkx as nx

        data = json.loads(config.graph_path.read_text())
        graph = nx.node_link_graph(data)
        return {"graph": graph}
    except Exception as e:
        logger.warning("Failed to load graph data: %s", e)
        return None


def _enrich_components(
    services: list[dict[str, Any]],
    libraries: list[dict[str, Any]],
    compose_info: dict[str, Any],
    graph_data: dict[str, Any] | None,
    repo_path: Path,
) -> list[dict[str, Any]]:
    """Merge all data sources into a unified component list."""
    components: list[dict[str, Any]] = []
    compose_deps = compose_info.get("dependencies", {})
    compose_services = compose_info.get("services_raw", {})

    # Process services
    for svc in services:
        comp = dict(svc)
        comp["display_type"] = svc.get("type", "service")

        # Add compose dependencies
        deps = compose_deps.get(svc["name"], [])
        if deps:
            comp["compose_depends_on"] = deps

        # Try to get richer description from service README
        readme_desc = _extract_readme_description(repo_path, svc.get("path", ""))
        if readme_desc and (
            not comp.get("description") or len(readme_desc) > len(comp.get("description", ""))
        ):
            comp["description"] = readme_desc

        # Enrich from graph data
        if graph_data:
            _enrich_from_graph(comp, graph_data)

        # Identify data stores this service uses (from compose depends_on)
        data_store_deps = []
        for dep in deps:
            dep_config = compose_services.get(dep, {})
            if _is_data_store_name(dep, dep_config):
                data_store_deps.append(dep)
        if data_store_deps:
            comp["data_stores"] = data_store_deps

        components.append(comp)

    # Process libraries
    for lib in libraries:
        comp = dict(lib)
        comp["display_type"] = "library"

        readme_desc = _extract_readme_description(repo_path, lib.get("path", ""))
        if readme_desc and (
            not comp.get("description") or len(readme_desc) > len(comp.get("description", ""))
        ):
            comp["description"] = readme_desc

        if graph_data:
            _enrich_from_graph(comp, graph_data)

        components.append(comp)

    # Add data stores from compose that aren't already in the list
    data_stores = compose_info.get("data_stores", [])
    existing_names = {c["name"] for c in components}
    for store in data_stores:
        if store["name"] not in existing_names:
            comp: dict[str, Any] = {
                "name": store["name"],
                "display_type": "data_store",
                "description": store["type"],
                "path": "",
            }
            if graph_data:
                _enrich_from_graph(comp, graph_data)
            components.append(comp)

    # Add init services from compose that aren't already in the list
    for svc_name, svc_config in compose_services.items():
        if svc_name not in existing_names and _is_init_service(svc_name, svc_config):
            comp = {
                "name": svc_name,
                "display_type": "init",
                "description": "",
                "path": "",
                "compose_depends_on": compose_deps.get(svc_name, []),
            }
            if graph_data:
                _enrich_from_graph(comp, graph_data)
            components.append(comp)
            existing_names.add(svc_name)

    return components


def _enrich_from_graph(comp: dict[str, Any], graph_data: dict[str, Any]) -> None:
    """Add upstream/downstream/gRPC info from the dependency graph."""
    graph = graph_data["graph"]
    name = comp["name"]

    if name not in graph:
        return

    node_attrs = dict(graph.nodes[name])

    # Upstream (what this component depends on)
    upstream = [succ for succ in graph.successors(name)]
    if upstream:
        comp["upstream_names"] = upstream

    # Downstream (what depends on this component)
    downstream = [pred for pred in graph.predecessors(name)]
    if downstream:
        comp["downstream_names"] = downstream

    # gRPC services
    grpc_services = node_attrs.get("grpc_services", [])
    if grpc_services:
        comp["grpc_services"] = grpc_services

    grpc_rpcs = node_attrs.get("grpc_rpcs", [])
    if grpc_rpcs:
        comp["grpc_rpcs"] = grpc_rpcs

    # Component type from graph (more accurate than dir-based detection)
    if node_attrs.get("component_type"):
        comp["graph_component_type"] = node_attrs["component_type"]

    # Package name
    if node_attrs.get("package_name"):
        comp["package_name"] = node_attrs["package_name"]

    # Graph description (from pyproject.toml, may be richer)
    graph_desc = node_attrs.get("description", "")
    if graph_desc and not comp.get("description"):
        comp["description"] = graph_desc


def _extract_readme_description(repo_path: Path, service_path: str) -> str:
    """Extract the first meaningful paragraph from a service's README.md."""
    if not service_path:
        return ""

    readme_path = repo_path / service_path / "README.md"
    if not readme_path.exists():
        # Try lowercase
        readme_path = repo_path / service_path / "readme.md"
    if not readme_path.exists():
        return ""

    try:
        content = readme_path.read_text(errors="replace")
    except Exception:
        return ""

    # Extract first non-heading, non-empty paragraph
    lines = content.splitlines()
    paragraph_lines: list[str] = []
    found_content = False

    for line in lines:
        stripped = line.strip()

        # Skip headings, badges, empty lines at the start
        if not found_content:
            if (
                not stripped
                or stripped.startswith("#")
                or stripped.startswith("![")
                or stripped.startswith("[!")
            ):
                continue
            found_content = True

        if found_content:
            if not stripped:
                # End of paragraph
                if paragraph_lines:
                    break
                continue
            if stripped.startswith("#"):
                # Next heading, stop
                break
            paragraph_lines.append(stripped)

    result = " ".join(paragraph_lines).strip()
    # Cap at a reasonable length
    if len(result) > 300:
        result = result[:297] + "..."
    return result


# --- Rendering helpers ---


def _render_component(comp: dict[str, Any]) -> str:
    """Render a single component as a markdown section."""
    lines: list[str] = []
    lines.append(f"### {comp['name']}\n")

    # Basic info line (compact)
    info_parts: list[str] = []
    if comp.get("path"):
        info_parts.append(f"**Path**: `{comp['path']}`")
    if comp.get("language"):
        info_parts.append(f"**Language**: {comp['language']}")
    if comp.get("framework"):
        info_parts.append(f"**Framework**: {comp['framework']}")
    if info_parts:
        lines.append("- " + " | ".join(info_parts))

    # Description
    if comp.get("description"):
        lines.append(f"- **Description**: {comp['description']}")

    # Dependencies (from graph or compose)
    upstream = comp.get("upstream_names", [])
    if not upstream:
        upstream = comp.get("compose_depends_on", [])
    if upstream:
        lines.append(f"- **Depends on**: {', '.join(upstream)}")

    # Dependents
    downstream = comp.get("downstream_names", [])
    if downstream:
        lines.append(f"- **Depended on by**: {', '.join(downstream)}")

    # Data stores
    data_stores = comp.get("data_stores", [])
    if data_stores:
        lines.append(f"- **Data stores**: {', '.join(data_stores)}")

    # gRPC services
    grpc = comp.get("grpc_services", [])
    if grpc:
        lines.append(f"- **gRPC services**: {', '.join(grpc)}")

    lines.append("")
    return "\n".join(lines)


def _build_quick_reference(components: list[dict[str, Any]]) -> str:
    """Build a compact quick reference table."""
    if not components:
        return ""

    lines: list[str] = []
    lines.append("| Component | Type | Language | Key Dependencies |")
    lines.append("|-----------|------|----------|-----------------|")

    for comp in components:
        name = comp["name"]
        ctype = comp.get("display_type", "")
        lang = comp.get("language", "")
        deps = comp.get("upstream_names", comp.get("compose_depends_on", []))
        deps_str = ", ".join(deps[:4])
        if len(deps) > 4:
            deps_str += f" (+{len(deps) - 4})"
        lines.append(f"| {name} | {ctype} | {lang} | {deps_str} |")

    return "\n".join(lines)


def _build_data_flow_section(graph_data: dict[str, Any] | None) -> str:
    """Build a data flow section from graph edges, grouped by type."""
    if not graph_data:
        return ""

    graph = graph_data["graph"]
    if graph.number_of_edges() == 0:
        return ""

    lines: list[str] = []
    lines.append("## Communication Patterns\n")

    # Group edges by type
    edge_groups: dict[str, list[tuple[str, str]]] = {}
    for src, tgt, attrs in graph.edges(data=True):
        edge_type = attrs.get("edge_type", "depends_on")
        if edge_type not in edge_groups:
            edge_groups[edge_type] = []
        edge_groups[edge_type].append((src, tgt))

    type_labels = {
        "depends_on": "Service Dependencies",
        "uses_datastore": "Data Store Usage",
        "grpc": "gRPC Communication",
        "library_dep": "Library Dependencies",
    }

    for edge_type, edges in edge_groups.items():
        label = type_labels.get(edge_type, edge_type)
        lines.append(f"### {label}\n")
        for src, tgt in edges:
            lines.append(f"- {src} -> {tgt}")
        lines.append("")

    return "\n".join(lines)


# --- Detection helpers ---


def _detect_services(repo_path: Path) -> list[dict[str, Any]]:
    """Detect microservices in the repo."""
    services: list[dict[str, Any]] = []

    services_dir = repo_path / "services"
    if services_dir.exists():
        for svc_dir in sorted(services_dir.iterdir()):
            if not svc_dir.is_dir() or svc_dir.name.startswith("."):
                continue
            svc: dict[str, Any] = {
                "name": svc_dir.name,
                "path": f"services/{svc_dir.name}",
                "type": "service",
            }
            _detect_service_tech(svc_dir, svc)
            services.append(svc)

    # Check for MCP servers
    mcp_dir = repo_path / "mcp_servers"
    if mcp_dir.exists():
        for svc_dir in sorted(mcp_dir.iterdir()):
            if not svc_dir.is_dir() or svc_dir.name.startswith("."):
                continue
            svc = {
                "name": svc_dir.name,
                "path": f"mcp_servers/{svc_dir.name}",
                "type": "mcp_server",
            }
            _detect_service_tech(svc_dir, svc)
            services.append(svc)

    # Check for agents
    agents_dir = repo_path / "agents"
    if agents_dir.exists():
        for svc_dir in sorted(agents_dir.iterdir()):
            if not svc_dir.is_dir() or svc_dir.name.startswith("."):
                continue
            svc = {
                "name": svc_dir.name,
                "path": f"agents/{svc_dir.name}",
                "type": "agent",
            }
            _detect_service_tech(svc_dir, svc)
            services.append(svc)

    return services


def _detect_service_tech(svc_dir: Path, svc: dict[str, Any]) -> None:
    """Detect language and framework for a service directory."""
    # Python
    if list(svc_dir.rglob("pyproject.toml")):
        svc["language"] = "python"
        for req_file in svc_dir.rglob("pyproject.toml"):
            try:
                content = req_file.read_text()
                if "fastapi" in content.lower():
                    svc["framework"] = "FastAPI"
                elif "flask" in content.lower():
                    svc["framework"] = "Flask"
                elif "langchain" in content.lower() or "langgraph" in content.lower():
                    svc["framework"] = "LangChain/LangGraph"
                # Try to extract description
                if "description" in content:
                    for line in content.splitlines():
                        if line.strip().startswith("description"):
                            desc = line.split("=", 1)[-1].strip().strip('"').strip("'")
                            if desc:
                                svc["description"] = desc
                            break
            except Exception:
                pass

    # Go
    elif list(svc_dir.rglob("go.mod")):
        svc["language"] = "go"
        for mod_file in svc_dir.rglob("go.mod"):
            try:
                content = mod_file.read_text()
                if "gin-gonic" in content:
                    svc["framework"] = "Gin"
            except Exception:
                pass

    # TypeScript/JavaScript
    elif list(svc_dir.rglob("package.json")):
        svc["language"] = "typescript"
        for pkg_file in svc_dir.rglob("package.json"):
            try:
                content = pkg_file.read_text()
                if "react" in content:
                    svc["framework"] = "React"
                elif "express" in content:
                    svc["framework"] = "Express"
                elif "next" in content:
                    svc["framework"] = "Next.js"
            except Exception:
                pass

    # Rust
    elif list(svc_dir.rglob("Cargo.toml")):
        svc["language"] = "rust"


def _detect_libraries(repo_path: Path) -> list[dict[str, Any]]:
    """Detect shared libraries."""
    libraries: list[dict[str, Any]] = []

    # Check common library directory names
    lib_dirs = ["libraries", "libs", "packages"]
    for lib_dir_name in lib_dirs:
        libs_dir = repo_path / lib_dir_name
        if not libs_dir.exists():
            continue
        # Handle nested structure like libraries/python/<lib>
        for child in sorted(libs_dir.iterdir()):
            if not child.is_dir() or child.name.startswith("."):
                continue
            # Check if this is a direct library or a language group
            if _has_project_file(child):
                lib = _build_lib_entry(child, f"{lib_dir_name}/{child.name}")
                libraries.append(lib)
            else:
                # Could be libraries/python/<lib>, libraries/go/<lib>, etc.
                for sub in sorted(child.iterdir()):
                    if not sub.is_dir() or sub.name.startswith("."):
                        continue
                    if _has_project_file(sub):
                        lib = _build_lib_entry(sub, f"{lib_dir_name}/{child.name}/{sub.name}")
                        libraries.append(lib)

    return libraries


def _has_project_file(directory: Path) -> bool:
    """Check if a directory has a project file (pyproject.toml, package.json, etc.)."""
    return any(
        (directory / f).exists() for f in ["pyproject.toml", "package.json", "Cargo.toml", "go.mod"]
    )


def _build_lib_entry(lib_dir: Path, rel_path: str) -> dict[str, Any]:
    """Build a library entry from a directory."""
    lib: dict[str, Any] = {
        "name": lib_dir.name,
        "path": rel_path,
    }
    # Try to get description from pyproject.toml
    for toml_file in lib_dir.rglob("pyproject.toml"):
        try:
            content = toml_file.read_text()
            for line in content.splitlines():
                if line.strip().startswith("description"):
                    desc = line.split("=", 1)[-1].strip().strip('"').strip("'")
                    if desc:
                        lib["description"] = desc
                    break
        except Exception:
            pass
    return lib


def _parse_compose(repo_path: Path) -> dict[str, Any]:
    """Parse Docker Compose file for service topology."""
    result: dict[str, Any] = {"data_stores": [], "dependencies": {}, "services_raw": {}}

    compose_file = repo_path / "compose.yml"
    if not compose_file.exists():
        compose_file = repo_path / "docker-compose.yml"
    if not compose_file.exists():
        compose_file = repo_path / "docker-compose.yaml"
    if not compose_file.exists():
        return result

    try:
        data = yaml.safe_load(compose_file.read_text())
    except Exception as e:
        logger.warning("Failed to parse compose file: %s", e)
        return result

    if not data or "services" not in data:
        return result

    # Known data store images
    data_store_patterns = {
        "postgres": "PostgreSQL",
        "timescaledb": "TimescaleDB",
        "neo4j": "Neo4j",
        "chromadb": "ChromaDB",
        "chroma": "ChromaDB",
        "redis": "Redis",
        "kafka": "Kafka",
        "minio": "MinIO/S3",
        "langfuse": "Langfuse",
    }

    for svc_name, svc_config in data.get("services", {}).items():
        if not isinstance(svc_config, dict):
            continue

        result["services_raw"][svc_name] = svc_config
        image = svc_config.get("image", "")

        # Detect data stores
        for pattern, store_type in data_store_patterns.items():
            if pattern in svc_name.lower() or pattern in image.lower():
                result["data_stores"].append({"name": svc_name, "type": store_type})
                break

        # Detect dependencies
        depends_on = svc_config.get("depends_on", [])
        if isinstance(depends_on, dict):
            deps = list(depends_on.keys())
        elif isinstance(depends_on, list):
            deps = depends_on
        else:
            deps = []

        if deps:
            result["dependencies"][svc_name] = deps

    return result


def _is_data_store_name(name: str, config: dict[str, Any]) -> bool:
    """Check if a compose service name looks like a data store."""
    image = ""
    if isinstance(config, dict):
        image = config.get("image", "")
    patterns = [
        "postgres",
        "timescaledb",
        "neo4j",
        "chromadb",
        "chroma",
        "redis",
        "kafka",
        "minio",
        "langfuse",
    ]
    for p in patterns:
        if p in name.lower() or p in image.lower():
            return True
    return False


def _is_init_service(name: str, config: dict[str, Any]) -> bool:
    """Check if a compose service is an init/migration service."""
    init_patterns = {"init", "migrations", "setup"}
    for pattern in init_patterns:
        if pattern in name.lower():
            return True
    if isinstance(config, dict) and config.get("restart") == "no":
        return True
    return False


def _detect_infrastructure(repo_path: Path) -> list[str]:
    """Detect infrastructure tooling."""
    infra: list[str] = []

    if (repo_path / "helm-charts").exists():
        chart_count = len(list((repo_path / "helm-charts").glob("*/Chart.yaml")))
        if chart_count == 0:
            # Try nested structure
            chart_count = len(list((repo_path / "helm-charts").rglob("Chart.yaml")))
        infra.append(f"Helm charts: {chart_count} charts")

    if (repo_path / "infrastructure").exists():
        infra.append("Infrastructure as Code (Terraform/OpenTofu)")

    if (repo_path / ".github" / "workflows").exists():
        wf_count = len(list((repo_path / ".github" / "workflows").glob("*.yml")))
        infra.append(f"GitHub Actions: {wf_count} workflows")

    if (repo_path / "justfile").exists():
        infra.append("Task runner: Just")

    if (repo_path / "Makefile").exists():
        infra.append("Task runner: Make")

    if (repo_path / "monitoring").exists():
        infra.append("Monitoring: Grafana + Prometheus")

    if (repo_path / "skaffold.yaml").exists():
        infra.append("Skaffold: local Kubernetes development")

    return infra
