"""Architecture document generator.

Analyzes repo structure and produces a starting architecture.md
and service_map.json that can be manually curated.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

import yaml

from repo_brain.config import RepoConfig

logger = logging.getLogger(__name__)


def generate_architecture(config: RepoConfig) -> str:
    """Analyze repo and generate architecture.md content."""
    repo_path = Path(config.path)
    sections: list[str] = []

    sections.append(f"# Architecture — {config.name}\n")
    sections.append(f"Repository: `{config.remote_url or config.path}`\n")
    sections.append("---\n")

    # Detect services
    services = _detect_services(repo_path)
    if services:
        sections.append("## Services\n")
        for svc in services:
            sections.append(f"### {svc['name']}\n")
            sections.append(f"- **Path**: `{svc['path']}`")
            sections.append(f"- **Type**: {svc['type']}")
            if svc.get("language"):
                sections.append(f"- **Language**: {svc['language']}")
            if svc.get("framework"):
                sections.append(f"- **Framework**: {svc['framework']}")
            if svc.get("description"):
                sections.append(f"- **Description**: {svc['description']}")
            sections.append("")

    # Detect shared libraries
    libraries = _detect_libraries(repo_path)
    if libraries:
        sections.append("## Shared Libraries\n")
        for lib in libraries:
            sections.append(f"### {lib['name']}\n")
            sections.append(f"- **Path**: `{lib['path']}`")
            if lib.get("description"):
                sections.append(f"- **Description**: {lib['description']}")
            sections.append("")

    # Detect data stores from compose
    compose_info = _parse_compose(repo_path)
    if compose_info.get("data_stores"):
        sections.append("## Data Stores\n")
        for store in compose_info["data_stores"]:
            sections.append(f"- **{store['name']}**: {store['type']}")
        sections.append("")

    # Detect infrastructure
    infra = _detect_infrastructure(repo_path)
    if infra:
        sections.append("## Infrastructure\n")
        for item in infra:
            sections.append(f"- {item}")
        sections.append("")

    sections.append("---\n")
    sections.append(
        "*This document was auto-generated by repo-brain. "
        "Edit it to add domain knowledge, gotchas, and design decisions.*\n"
    )

    return "\n".join(sections)


def generate_service_map(config: RepoConfig) -> dict[str, Any]:
    """Generate a structured service map as JSON."""
    repo_path = Path(config.path)

    services = _detect_services(repo_path)
    libraries = _detect_libraries(repo_path)
    compose_info = _parse_compose(repo_path)

    service_map: dict[str, Any] = {
        "repo": config.name,
        "services": {},
        "libraries": {},
        "data_stores": compose_info.get("data_stores", []),
        "service_dependencies": compose_info.get("dependencies", {}),
    }

    for svc in services:
        service_map["services"][svc["name"]] = {
            "path": svc["path"],
            "type": svc["type"],
            "language": svc.get("language", ""),
            "framework": svc.get("framework", ""),
            "dependencies": compose_info.get("dependencies", {}).get(svc["name"], []),
            "data_stores": [],
        }

    for lib in libraries:
        service_map["libraries"][lib["name"]] = {
            "path": lib["path"],
            "description": lib.get("description", ""),
        }

    return service_map


def save_generated_docs(config: RepoConfig) -> dict[str, str]:
    """Generate and save all architecture docs. Returns paths of created files."""
    config.docs_dir.mkdir(parents=True, exist_ok=True)
    created: dict[str, str] = {}

    # architecture.md
    arch_path = config.docs_dir / "architecture.md"
    arch_content = generate_architecture(config)
    arch_path.write_text(arch_content)
    created["architecture.md"] = str(arch_path)

    # service_map.json
    map_path = config.docs_dir / "service_map.json"
    service_map = generate_service_map(config)
    map_path.write_text(json.dumps(service_map, indent=2))
    created["service_map.json"] = str(map_path)

    # domain_terms.md (skeleton)
    terms_path = config.docs_dir / "domain_terms.md"
    if not terms_path.exists():
        terms_path.write_text(
            f"# Domain Terms — {config.name}\n\n"
            "Add business vocabulary and internal naming conventions here.\n\n"
            "| Term | Meaning |\n"
            "|------|--------|\n"
            "| | |\n"
        )
        created["domain_terms.md"] = str(terms_path)

    # gotchas.md (skeleton)
    gotchas_path = config.docs_dir / "gotchas.md"
    if not gotchas_path.exists():
        gotchas_path.write_text(
            f"# Gotchas — {config.name}\n\n"
            "Document traps, edge cases, and common mistakes here.\n\n"
            "## Known Issues\n\n"
            "## Common Mistakes\n\n"
            "## Edge Cases\n"
        )
        created["gotchas.md"] = str(gotchas_path)

    return created


# --- Internal helpers ---


def _detect_services(repo_path: Path) -> list[dict[str, Any]]:
    """Detect microservices in the repo."""
    services: list[dict[str, Any]] = []

    services_dir = repo_path / "services"
    if services_dir.exists():
        for svc_dir in sorted(services_dir.iterdir()):
            if not svc_dir.is_dir() or svc_dir.name.startswith("."):
                continue
            svc: dict[str, Any] = {
                "name": svc_dir.name,
                "path": f"services/{svc_dir.name}",
                "type": "service",
            }
            # Detect language/framework
            _detect_service_tech(svc_dir, svc)
            services.append(svc)

    # Check for MCP servers
    mcp_dir = repo_path / "mcp_servers"
    if mcp_dir.exists():
        for svc_dir in sorted(mcp_dir.iterdir()):
            if not svc_dir.is_dir() or svc_dir.name.startswith("."):
                continue
            svc = {
                "name": svc_dir.name,
                "path": f"mcp_servers/{svc_dir.name}",
                "type": "mcp_server",
            }
            _detect_service_tech(svc_dir, svc)
            services.append(svc)

    # Check for agents
    agents_dir = repo_path / "agents"
    if agents_dir.exists():
        for svc_dir in sorted(agents_dir.iterdir()):
            if not svc_dir.is_dir() or svc_dir.name.startswith("."):
                continue
            svc = {
                "name": svc_dir.name,
                "path": f"agents/{svc_dir.name}",
                "type": "agent",
            }
            _detect_service_tech(svc_dir, svc)
            services.append(svc)

    return services


def _detect_service_tech(svc_dir: Path, svc: dict[str, Any]) -> None:
    """Detect language and framework for a service directory."""
    # Python
    if list(svc_dir.rglob("pyproject.toml")):
        svc["language"] = "python"
        # Check for FastAPI
        for req_file in svc_dir.rglob("pyproject.toml"):
            try:
                content = req_file.read_text()
                if "fastapi" in content.lower():
                    svc["framework"] = "FastAPI"
                elif "flask" in content.lower():
                    svc["framework"] = "Flask"
                elif "langchain" in content.lower() or "langgraph" in content.lower():
                    svc["framework"] = "LangChain/LangGraph"
                # Try to extract description
                if "description" in content:
                    for line in content.splitlines():
                        if line.strip().startswith("description"):
                            desc = line.split("=", 1)[-1].strip().strip('"').strip("'")
                            if desc:
                                svc["description"] = desc
                            break
            except Exception:
                pass

    # Go
    elif list(svc_dir.rglob("go.mod")):
        svc["language"] = "go"
        for mod_file in svc_dir.rglob("go.mod"):
            try:
                content = mod_file.read_text()
                if "gin-gonic" in content:
                    svc["framework"] = "Gin"
            except Exception:
                pass

    # TypeScript/JavaScript
    elif list(svc_dir.rglob("package.json")):
        svc["language"] = "typescript"
        for pkg_file in svc_dir.rglob("package.json"):
            try:
                content = pkg_file.read_text()
                if "react" in content:
                    svc["framework"] = "React"
                elif "express" in content:
                    svc["framework"] = "Express"
                elif "next" in content:
                    svc["framework"] = "Next.js"
            except Exception:
                pass

    # Rust
    elif list(svc_dir.rglob("Cargo.toml")):
        svc["language"] = "rust"


def _detect_libraries(repo_path: Path) -> list[dict[str, Any]]:
    """Detect shared libraries."""
    libraries: list[dict[str, Any]] = []

    libs_dir = repo_path / "libraries"
    if libs_dir.exists():
        for lib_dir in sorted(libs_dir.iterdir()):
            if not lib_dir.is_dir() or lib_dir.name.startswith("."):
                continue
            lib: dict[str, Any] = {
                "name": lib_dir.name,
                "path": f"libraries/{lib_dir.name}",
            }
            # Try to get description from pyproject.toml
            for toml_file in lib_dir.rglob("pyproject.toml"):
                try:
                    content = toml_file.read_text()
                    for line in content.splitlines():
                        if line.strip().startswith("description"):
                            desc = line.split("=", 1)[-1].strip().strip('"').strip("'")
                            if desc:
                                lib["description"] = desc
                            break
                except Exception:
                    pass
            libraries.append(lib)

    return libraries


def _parse_compose(repo_path: Path) -> dict[str, Any]:
    """Parse Docker Compose file for service topology."""
    result: dict[str, Any] = {"data_stores": [], "dependencies": {}}

    compose_file = repo_path / "compose.yml"
    if not compose_file.exists():
        compose_file = repo_path / "docker-compose.yml"
    if not compose_file.exists():
        return result

    try:
        data = yaml.safe_load(compose_file.read_text())
    except Exception as e:
        logger.warning("Failed to parse compose file: %s", e)
        return result

    if not data or "services" not in data:
        return result

    # Known data store images
    data_store_patterns = {
        "postgres": "PostgreSQL",
        "timescaledb": "TimescaleDB",
        "neo4j": "Neo4j",
        "chromadb": "ChromaDB",
        "chroma": "ChromaDB",
        "redis": "Redis",
        "kafka": "Kafka",
        "minio": "MinIO/S3",
        "langfuse": "Langfuse",
    }

    for svc_name, svc_config in data.get("services", {}).items():
        if not isinstance(svc_config, dict):
            continue

        image = svc_config.get("image", "")

        # Detect data stores
        for pattern, store_type in data_store_patterns.items():
            if pattern in svc_name.lower() or pattern in image.lower():
                result["data_stores"].append({"name": svc_name, "type": store_type})
                break

        # Detect dependencies
        depends_on = svc_config.get("depends_on", [])
        if isinstance(depends_on, dict):
            deps = list(depends_on.keys())
        elif isinstance(depends_on, list):
            deps = depends_on
        else:
            deps = []

        if deps:
            result["dependencies"][svc_name] = deps

    return result


def _detect_infrastructure(repo_path: Path) -> list[str]:
    """Detect infrastructure tooling."""
    infra: list[str] = []

    if (repo_path / "helm-charts").exists():
        chart_count = len(list((repo_path / "helm-charts").glob("*/Chart.yaml")))
        infra.append(f"Helm charts: {chart_count} charts")

    if (repo_path / "infrastructure").exists():
        infra.append("Infrastructure as Code (Terraform/OpenTofu)")

    if (repo_path / ".github" / "workflows").exists():
        wf_count = len(list((repo_path / ".github" / "workflows").glob("*.yml")))
        infra.append(f"GitHub Actions: {wf_count} workflows")

    if (repo_path / "justfile").exists():
        infra.append("Task runner: Just")

    if (repo_path / "Makefile").exists():
        infra.append("Task runner: Make")

    if (repo_path / "monitoring").exists():
        infra.append("Monitoring: Grafana + Prometheus")

    return infra
